#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PortailServices")]
public partial class DataAccesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Définitions de méthodes d'extensibilité
  partial void OnCreated();
  partial void Insertadresse(adresse instance);
  partial void Updateadresse(adresse instance);
  partial void Deleteadresse(adresse instance);
  partial void Insertaffecter(affecter instance);
  partial void Updateaffecter(affecter instance);
  partial void Deleteaffecter(affecter instance);
  partial void Insertbranche(branche instance);
  partial void Updatebranche(branche instance);
  partial void Deletebranche(branche instance);
  partial void Insertdestination(destination instance);
  partial void Updatedestination(destination instance);
  partial void Deletedestination(destination instance);
  partial void InsertDetailCommande(DetailCommande instance);
  partial void UpdateDetailCommande(DetailCommande instance);
  partial void DeleteDetailCommande(DetailCommande instance);
  partial void Insertnotification(notification instance);
  partial void Updatenotification(notification instance);
  partial void Deletenotification(notification instance);
  partial void Insertpartenaire(partenaire instance);
  partial void Updatepartenaire(partenaire instance);
  partial void Deletepartenaire(partenaire instance);
  partial void Insertpermission(permission instance);
  partial void Updatepermission(permission instance);
  partial void Deletepermission(permission instance);
  partial void Insertproduit(produit instance);
  partial void Updateproduit(produit instance);
  partial void Deleteproduit(produit instance);
  partial void Insertprofil(profil instance);
  partial void Updateprofil(profil instance);
  partial void Deleteprofil(profil instance);
  partial void InsertrecuperationMDP(recuperationMDP instance);
  partial void UpdaterecuperationMDP(recuperationMDP instance);
  partial void DeleterecuperationMDP(recuperationMDP instance);
  partial void Insertservice(service instance);
  partial void Updateservice(service instance);
  partial void Deleteservice(service instance);
  partial void Insertsous_branche(sous_branche instance);
  partial void Updatesous_branche(sous_branche instance);
  partial void Deletesous_branche(sous_branche instance);
  partial void Inserttype_interaction(type_interaction instance);
  partial void Updatetype_interaction(type_interaction instance);
  partial void Deletetype_interaction(type_interaction instance);
  partial void Inserttype_service(type_service instance);
  partial void Updatetype_service(type_service instance);
  partial void Deletetype_service(type_service instance);
  partial void InsertUtilisateur(Utilisateur instance);
  partial void UpdateUtilisateur(Utilisateur instance);
  partial void DeleteUtilisateur(Utilisateur instance);
  #endregion
	
	public DataAccesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PortailServicesConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataAccesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataAccesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataAccesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataAccesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<adresse> adresse
	{
		get
		{
			return this.GetTable<adresse>();
		}
	}
	
	public System.Data.Linq.Table<affecter> affecter
	{
		get
		{
			return this.GetTable<affecter>();
		}
	}
	
	public System.Data.Linq.Table<branche> branche
	{
		get
		{
			return this.GetTable<branche>();
		}
	}
	
	public System.Data.Linq.Table<destination> destination
	{
		get
		{
			return this.GetTable<destination>();
		}
	}
	
	public System.Data.Linq.Table<DetailCommande> DetailCommande
	{
		get
		{
			return this.GetTable<DetailCommande>();
		}
	}
	
	public System.Data.Linq.Table<notification> notification
	{
		get
		{
			return this.GetTable<notification>();
		}
	}
	
	public System.Data.Linq.Table<partenaire> partenaire
	{
		get
		{
			return this.GetTable<partenaire>();
		}
	}
	
	public System.Data.Linq.Table<permission> permission
	{
		get
		{
			return this.GetTable<permission>();
		}
	}
	
	public System.Data.Linq.Table<produit> produit
	{
		get
		{
			return this.GetTable<produit>();
		}
	}
	
	public System.Data.Linq.Table<profil> profil
	{
		get
		{
			return this.GetTable<profil>();
		}
	}
	
	public System.Data.Linq.Table<recuperationMDP> recuperationMDP
	{
		get
		{
			return this.GetTable<recuperationMDP>();
		}
	}
	
	public System.Data.Linq.Table<service> service
	{
		get
		{
			return this.GetTable<service>();
		}
	}
	
	public System.Data.Linq.Table<sous_branche> sous_branche
	{
		get
		{
			return this.GetTable<sous_branche>();
		}
	}
	
	public System.Data.Linq.Table<statistique> statistique
	{
		get
		{
			return this.GetTable<statistique>();
		}
	}
	
	public System.Data.Linq.Table<type_interaction> type_interaction
	{
		get
		{
			return this.GetTable<type_interaction>();
		}
	}
	
	public System.Data.Linq.Table<type_service> type_service
	{
		get
		{
			return this.GetTable<type_service>();
		}
	}
	
	public System.Data.Linq.Table<Utilisateur> Utilisateur
	{
		get
		{
			return this.GetTable<Utilisateur>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.adresse")]
public partial class adresse : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_adresse;
	
	private string _rue;
	
	private string _code_postal;
	
	private string _ville;
	
	private string _gouvernerat;
	
	private string _tel;
	
	private string _fax;
	
	private string _email;
	
	private EntitySet<recuperationMDP> _recuperationMDP;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_adresseChanging(int value);
    partial void Oncode_adresseChanged();
    partial void OnrueChanging(string value);
    partial void OnrueChanged();
    partial void Oncode_postalChanging(string value);
    partial void Oncode_postalChanged();
    partial void OnvilleChanging(string value);
    partial void OnvilleChanged();
    partial void OngouverneratChanging(string value);
    partial void OngouverneratChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
	
	public adresse()
	{
		this._recuperationMDP = new EntitySet<recuperationMDP>(new Action<recuperationMDP>(this.attach_recuperationMDP), new Action<recuperationMDP>(this.detach_recuperationMDP));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_adresse", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_adresse
	{
		get
		{
			return this._code_adresse;
		}
		set
		{
			if ((this._code_adresse != value))
			{
				this.Oncode_adresseChanging(value);
				this.SendPropertyChanging();
				this._code_adresse = value;
				this.SendPropertyChanged("code_adresse");
				this.Oncode_adresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rue", DbType="NVarChar(50)")]
	public string rue
	{
		get
		{
			return this._rue;
		}
		set
		{
			if ((this._rue != value))
			{
				this.OnrueChanging(value);
				this.SendPropertyChanging();
				this._rue = value;
				this.SendPropertyChanged("rue");
				this.OnrueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_postal", DbType="NVarChar(50)")]
	public string code_postal
	{
		get
		{
			return this._code_postal;
		}
		set
		{
			if ((this._code_postal != value))
			{
				this.Oncode_postalChanging(value);
				this.SendPropertyChanging();
				this._code_postal = value;
				this.SendPropertyChanged("code_postal");
				this.Oncode_postalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ville", DbType="NVarChar(50)")]
	public string ville
	{
		get
		{
			return this._ville;
		}
		set
		{
			if ((this._ville != value))
			{
				this.OnvilleChanging(value);
				this.SendPropertyChanging();
				this._ville = value;
				this.SendPropertyChanged("ville");
				this.OnvilleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gouvernerat", DbType="NVarChar(50)")]
	public string gouvernerat
	{
		get
		{
			return this._gouvernerat;
		}
		set
		{
			if ((this._gouvernerat != value))
			{
				this.OngouverneratChanging(value);
				this.SendPropertyChanging();
				this._gouvernerat = value;
				this.SendPropertyChanged("gouvernerat");
				this.OngouverneratChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="NVarChar(50)")]
	public string tel
	{
		get
		{
			return this._tel;
		}
		set
		{
			if ((this._tel != value))
			{
				this.OntelChanging(value);
				this.SendPropertyChanging();
				this._tel = value;
				this.SendPropertyChanged("tel");
				this.OntelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="NVarChar(50)")]
	public string fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adresse_recuperationMDP", Storage="_recuperationMDP", ThisKey="code_adresse", OtherKey="code_adresse")]
	public EntitySet<recuperationMDP> recuperationMDP
	{
		get
		{
			return this._recuperationMDP;
		}
		set
		{
			this._recuperationMDP.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_recuperationMDP(recuperationMDP entity)
	{
		this.SendPropertyChanging();
		entity.adresse = this;
	}
	
	private void detach_recuperationMDP(recuperationMDP entity)
	{
		this.SendPropertyChanging();
		entity.adresse = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.affecter")]
public partial class affecter : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_profil;
	
	private int _code_permission;
	
	private EntityRef<permission> _permission;
	
	private EntityRef<profil> _profil;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_profilChanging(int value);
    partial void Oncode_profilChanged();
    partial void Oncode_permissionChanging(int value);
    partial void Oncode_permissionChanged();
    #endregion
	
	public affecter()
	{
		this._permission = default(EntityRef<permission>);
		this._profil = default(EntityRef<profil>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_profil", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_profil
	{
		get
		{
			return this._code_profil;
		}
		set
		{
			if ((this._code_profil != value))
			{
				if (this._profil.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_profilChanging(value);
				this.SendPropertyChanging();
				this._code_profil = value;
				this.SendPropertyChanged("code_profil");
				this.Oncode_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_permission", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_permission
	{
		get
		{
			return this._code_permission;
		}
		set
		{
			if ((this._code_permission != value))
			{
				if (this._permission.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_permissionChanging(value);
				this.SendPropertyChanging();
				this._code_permission = value;
				this.SendPropertyChanged("code_permission");
				this.Oncode_permissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="permission_affecter", Storage="_permission", ThisKey="code_permission", OtherKey="code_permission", IsForeignKey=true)]
	public permission permission
	{
		get
		{
			return this._permission.Entity;
		}
		set
		{
			permission previousValue = this._permission.Entity;
			if (((previousValue != value) 
						|| (this._permission.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._permission.Entity = null;
					previousValue.affecter.Remove(this);
				}
				this._permission.Entity = value;
				if ((value != null))
				{
					value.affecter.Add(this);
					this._code_permission = value.code_permission;
				}
				else
				{
					this._code_permission = default(int);
				}
				this.SendPropertyChanged("permission");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_affecter", Storage="_profil", ThisKey="code_profil", OtherKey="code_profil", IsForeignKey=true)]
	public profil profil
	{
		get
		{
			return this._profil.Entity;
		}
		set
		{
			profil previousValue = this._profil.Entity;
			if (((previousValue != value) 
						|| (this._profil.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._profil.Entity = null;
					previousValue.affecter.Remove(this);
				}
				this._profil.Entity = value;
				if ((value != null))
				{
					value.affecter.Add(this);
					this._code_profil = value.code_profil;
				}
				else
				{
					this._code_profil = default(int);
				}
				this.SendPropertyChanged("profil");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.branche")]
public partial class branche : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_branche;
	
	private string _libelle;
	
	private EntitySet<sous_branche> _sous_branche;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_brancheChanging(int value);
    partial void OnId_brancheChanged();
    partial void OnlibelleChanging(string value);
    partial void OnlibelleChanged();
    #endregion
	
	public branche()
	{
		this._sous_branche = new EntitySet<sous_branche>(new Action<sous_branche>(this.attach_sous_branche), new Action<sous_branche>(this.detach_sous_branche));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_branche", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id_branche
	{
		get
		{
			return this._Id_branche;
		}
		set
		{
			if ((this._Id_branche != value))
			{
				this.OnId_brancheChanging(value);
				this.SendPropertyChanging();
				this._Id_branche = value;
				this.SendPropertyChanged("Id_branche");
				this.OnId_brancheChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelle", DbType="NVarChar(50)")]
	public string libelle
	{
		get
		{
			return this._libelle;
		}
		set
		{
			if ((this._libelle != value))
			{
				this.OnlibelleChanging(value);
				this.SendPropertyChanging();
				this._libelle = value;
				this.SendPropertyChanged("libelle");
				this.OnlibelleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="branche_sous_branche", Storage="_sous_branche", ThisKey="Id_branche", OtherKey="Id_branche")]
	public EntitySet<sous_branche> sous_branche
	{
		get
		{
			return this._sous_branche;
		}
		set
		{
			this._sous_branche.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_sous_branche(sous_branche entity)
	{
		this.SendPropertyChanging();
		entity.branche = this;
	}
	
	private void detach_sous_branche(sous_branche entity)
	{
		this.SendPropertyChanging();
		entity.branche = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.destination")]
public partial class destination : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_dest;
	
	private string _LibelleDest;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_destChanging(int value);
    partial void Oncode_destChanged();
    partial void OnLibelleDestChanging(string value);
    partial void OnLibelleDestChanged();
    #endregion
	
	public destination()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_dest", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_dest
	{
		get
		{
			return this._code_dest;
		}
		set
		{
			if ((this._code_dest != value))
			{
				this.Oncode_destChanging(value);
				this.SendPropertyChanging();
				this._code_dest = value;
				this.SendPropertyChanged("code_dest");
				this.Oncode_destChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibelleDest", DbType="NVarChar(50)")]
	public string LibelleDest
	{
		get
		{
			return this._LibelleDest;
		}
		set
		{
			if ((this._LibelleDest != value))
			{
				this.OnLibelleDestChanging(value);
				this.SendPropertyChanging();
				this._LibelleDest = value;
				this.SendPropertyChanged("LibelleDest");
				this.OnLibelleDestChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DetailCommande")]
public partial class DetailCommande : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_detail;
	
	private System.Nullable<int> _id_produit;
	
	private System.Nullable<int> _Qte;
	
	private System.Nullable<int> _QteLivree;
	
	private string _Observation;
	
	private System.Nullable<int> _code_service;
	
	private System.Nullable<int> _PU;
	
	private string _reponse;
	
	private EntityRef<produit> _produit;
	
	private EntityRef<service> _service;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_detailChanging(int value);
    partial void OnId_detailChanged();
    partial void Onid_produitChanging(System.Nullable<int> value);
    partial void Onid_produitChanged();
    partial void OnQteChanging(System.Nullable<int> value);
    partial void OnQteChanged();
    partial void OnQteLivreeChanging(System.Nullable<int> value);
    partial void OnQteLivreeChanged();
    partial void OnObservationChanging(string value);
    partial void OnObservationChanged();
    partial void Oncode_serviceChanging(System.Nullable<int> value);
    partial void Oncode_serviceChanged();
    partial void OnPUChanging(System.Nullable<int> value);
    partial void OnPUChanged();
    partial void OnreponseChanging(string value);
    partial void OnreponseChanged();
    #endregion
	
	public DetailCommande()
	{
		this._produit = default(EntityRef<produit>);
		this._service = default(EntityRef<service>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_detail", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id_detail
	{
		get
		{
			return this._Id_detail;
		}
		set
		{
			if ((this._Id_detail != value))
			{
				this.OnId_detailChanging(value);
				this.SendPropertyChanging();
				this._Id_detail = value;
				this.SendPropertyChanged("Id_detail");
				this.OnId_detailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_produit", DbType="Int")]
	public System.Nullable<int> id_produit
	{
		get
		{
			return this._id_produit;
		}
		set
		{
			if ((this._id_produit != value))
			{
				if (this._produit.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_produitChanging(value);
				this.SendPropertyChanging();
				this._id_produit = value;
				this.SendPropertyChanged("id_produit");
				this.Onid_produitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qte", DbType="Int")]
	public System.Nullable<int> Qte
	{
		get
		{
			return this._Qte;
		}
		set
		{
			if ((this._Qte != value))
			{
				this.OnQteChanging(value);
				this.SendPropertyChanging();
				this._Qte = value;
				this.SendPropertyChanged("Qte");
				this.OnQteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QteLivree", DbType="Int")]
	public System.Nullable<int> QteLivree
	{
		get
		{
			return this._QteLivree;
		}
		set
		{
			if ((this._QteLivree != value))
			{
				this.OnQteLivreeChanging(value);
				this.SendPropertyChanging();
				this._QteLivree = value;
				this.SendPropertyChanged("QteLivree");
				this.OnQteLivreeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observation", DbType="NVarChar(50)")]
	public string Observation
	{
		get
		{
			return this._Observation;
		}
		set
		{
			if ((this._Observation != value))
			{
				this.OnObservationChanging(value);
				this.SendPropertyChanging();
				this._Observation = value;
				this.SendPropertyChanged("Observation");
				this.OnObservationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_service", DbType="Int")]
	public System.Nullable<int> code_service
	{
		get
		{
			return this._code_service;
		}
		set
		{
			if ((this._code_service != value))
			{
				if (this._service.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_serviceChanging(value);
				this.SendPropertyChanging();
				this._code_service = value;
				this.SendPropertyChanged("code_service");
				this.Oncode_serviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PU", DbType="Int")]
	public System.Nullable<int> PU
	{
		get
		{
			return this._PU;
		}
		set
		{
			if ((this._PU != value))
			{
				this.OnPUChanging(value);
				this.SendPropertyChanging();
				this._PU = value;
				this.SendPropertyChanged("PU");
				this.OnPUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reponse", DbType="NVarChar(50)")]
	public string reponse
	{
		get
		{
			return this._reponse;
		}
		set
		{
			if ((this._reponse != value))
			{
				this.OnreponseChanging(value);
				this.SendPropertyChanging();
				this._reponse = value;
				this.SendPropertyChanged("reponse");
				this.OnreponseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produit_DetailCommande", Storage="_produit", ThisKey="id_produit", OtherKey="Id_produit", IsForeignKey=true)]
	public produit produit
	{
		get
		{
			return this._produit.Entity;
		}
		set
		{
			produit previousValue = this._produit.Entity;
			if (((previousValue != value) 
						|| (this._produit.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._produit.Entity = null;
					previousValue.DetailCommande.Remove(this);
				}
				this._produit.Entity = value;
				if ((value != null))
				{
					value.DetailCommande.Add(this);
					this._id_produit = value.Id_produit;
				}
				else
				{
					this._id_produit = default(Nullable<int>);
				}
				this.SendPropertyChanged("produit");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="service_DetailCommande", Storage="_service", ThisKey="code_service", OtherKey="code_service", IsForeignKey=true)]
	public service service
	{
		get
		{
			return this._service.Entity;
		}
		set
		{
			service previousValue = this._service.Entity;
			if (((previousValue != value) 
						|| (this._service.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._service.Entity = null;
					previousValue.DetailCommande.Remove(this);
				}
				this._service.Entity = value;
				if ((value != null))
				{
					value.DetailCommande.Add(this);
					this._code_service = value.code_service;
				}
				else
				{
					this._code_service = default(Nullable<int>);
				}
				this.SendPropertyChanged("service");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.notification")]
public partial class notification : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_notification;
	
	private string _contenu_notification;
	
	private string _etat;
	
	private System.Nullable<System.DateTime> _date_notification;
	
	private System.Nullable<int> _code_service;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_notificationChanging(int value);
    partial void Oncode_notificationChanged();
    partial void Oncontenu_notificationChanging(string value);
    partial void Oncontenu_notificationChanged();
    partial void OnetatChanging(string value);
    partial void OnetatChanged();
    partial void Ondate_notificationChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_notificationChanged();
    partial void Oncode_serviceChanging(System.Nullable<int> value);
    partial void Oncode_serviceChanged();
    #endregion
	
	public notification()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_notification", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int code_notification
	{
		get
		{
			return this._code_notification;
		}
		set
		{
			if ((this._code_notification != value))
			{
				this.Oncode_notificationChanging(value);
				this.SendPropertyChanging();
				this._code_notification = value;
				this.SendPropertyChanged("code_notification");
				this.Oncode_notificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contenu_notification", DbType="NVarChar(50)")]
	public string contenu_notification
	{
		get
		{
			return this._contenu_notification;
		}
		set
		{
			if ((this._contenu_notification != value))
			{
				this.Oncontenu_notificationChanging(value);
				this.SendPropertyChanging();
				this._contenu_notification = value;
				this.SendPropertyChanged("contenu_notification");
				this.Oncontenu_notificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etat", DbType="NVarChar(50)")]
	public string etat
	{
		get
		{
			return this._etat;
		}
		set
		{
			if ((this._etat != value))
			{
				this.OnetatChanging(value);
				this.SendPropertyChanging();
				this._etat = value;
				this.SendPropertyChanged("etat");
				this.OnetatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_notification", DbType="Date")]
	public System.Nullable<System.DateTime> date_notification
	{
		get
		{
			return this._date_notification;
		}
		set
		{
			if ((this._date_notification != value))
			{
				this.Ondate_notificationChanging(value);
				this.SendPropertyChanging();
				this._date_notification = value;
				this.SendPropertyChanged("date_notification");
				this.Ondate_notificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_service", DbType="Int")]
	public System.Nullable<int> code_service
	{
		get
		{
			return this._code_service;
		}
		set
		{
			if ((this._code_service != value))
			{
				this.Oncode_serviceChanging(value);
				this.SendPropertyChanging();
				this._code_service = value;
				this.SendPropertyChanged("code_service");
				this.Oncode_serviceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.partenaire")]
public partial class partenaire : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_partenaire;
	
	private System.Nullable<int> _code_adresse;
	
	private System.Nullable<int> _code_interaction;
	
	private string _titre_partenaire;
	
	private string _description_profil;
	
	private EntitySet<Utilisateur> _Utilisateur;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_partenaireChanging(int value);
    partial void Oncode_partenaireChanged();
    partial void Oncode_adresseChanging(System.Nullable<int> value);
    partial void Oncode_adresseChanged();
    partial void Oncode_interactionChanging(System.Nullable<int> value);
    partial void Oncode_interactionChanged();
    partial void Ontitre_partenaireChanging(string value);
    partial void Ontitre_partenaireChanged();
    partial void Ondescription_profilChanging(string value);
    partial void Ondescription_profilChanged();
    #endregion
	
	public partenaire()
	{
		this._Utilisateur = new EntitySet<Utilisateur>(new Action<Utilisateur>(this.attach_Utilisateur), new Action<Utilisateur>(this.detach_Utilisateur));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_partenaire", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_partenaire
	{
		get
		{
			return this._code_partenaire;
		}
		set
		{
			if ((this._code_partenaire != value))
			{
				this.Oncode_partenaireChanging(value);
				this.SendPropertyChanging();
				this._code_partenaire = value;
				this.SendPropertyChanged("code_partenaire");
				this.Oncode_partenaireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_adresse", DbType="Int")]
	public System.Nullable<int> code_adresse
	{
		get
		{
			return this._code_adresse;
		}
		set
		{
			if ((this._code_adresse != value))
			{
				this.Oncode_adresseChanging(value);
				this.SendPropertyChanging();
				this._code_adresse = value;
				this.SendPropertyChanged("code_adresse");
				this.Oncode_adresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_interaction", DbType="Int")]
	public System.Nullable<int> code_interaction
	{
		get
		{
			return this._code_interaction;
		}
		set
		{
			if ((this._code_interaction != value))
			{
				this.Oncode_interactionChanging(value);
				this.SendPropertyChanging();
				this._code_interaction = value;
				this.SendPropertyChanged("code_interaction");
				this.Oncode_interactionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_titre_partenaire", DbType="NVarChar(255)")]
	public string titre_partenaire
	{
		get
		{
			return this._titre_partenaire;
		}
		set
		{
			if ((this._titre_partenaire != value))
			{
				this.Ontitre_partenaireChanging(value);
				this.SendPropertyChanging();
				this._titre_partenaire = value;
				this.SendPropertyChanged("titre_partenaire");
				this.Ontitre_partenaireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description_profil", DbType="NVarChar(255)")]
	public string description_profil
	{
		get
		{
			return this._description_profil;
		}
		set
		{
			if ((this._description_profil != value))
			{
				this.Ondescription_profilChanging(value);
				this.SendPropertyChanging();
				this._description_profil = value;
				this.SendPropertyChanged("description_profil");
				this.Ondescription_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partenaire_Utilisateur", Storage="_Utilisateur", ThisKey="code_partenaire", OtherKey="code_partenaire")]
	public EntitySet<Utilisateur> Utilisateur
	{
		get
		{
			return this._Utilisateur;
		}
		set
		{
			this._Utilisateur.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Utilisateur(Utilisateur entity)
	{
		this.SendPropertyChanging();
		entity.partenaire = this;
	}
	
	private void detach_Utilisateur(Utilisateur entity)
	{
		this.SendPropertyChanging();
		entity.partenaire = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.permission")]
public partial class permission : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_permission;
	
	private string _description;
	
	private EntitySet<affecter> _affecter;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_permissionChanging(int value);
    partial void Oncode_permissionChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
	
	public permission()
	{
		this._affecter = new EntitySet<affecter>(new Action<affecter>(this.attach_affecter), new Action<affecter>(this.detach_affecter));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_permission", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_permission
	{
		get
		{
			return this._code_permission;
		}
		set
		{
			if ((this._code_permission != value))
			{
				this.Oncode_permissionChanging(value);
				this.SendPropertyChanging();
				this._code_permission = value;
				this.SendPropertyChanged("code_permission");
				this.Oncode_permissionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(50)")]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="permission_affecter", Storage="_affecter", ThisKey="code_permission", OtherKey="code_permission")]
	public EntitySet<affecter> affecter
	{
		get
		{
			return this._affecter;
		}
		set
		{
			this._affecter.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_affecter(affecter entity)
	{
		this.SendPropertyChanging();
		entity.permission = this;
	}
	
	private void detach_affecter(affecter entity)
	{
		this.SendPropertyChanging();
		entity.permission = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.produit")]
public partial class produit : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_produit;
	
	private string _LibelleProduit;
	
	private System.Nullable<int> _code_profil;
	
	private EntitySet<DetailCommande> _DetailCommande;
	
	private EntityRef<profil> _profil;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_produitChanging(int value);
    partial void OnId_produitChanged();
    partial void OnLibelleProduitChanging(string value);
    partial void OnLibelleProduitChanged();
    partial void Oncode_profilChanging(System.Nullable<int> value);
    partial void Oncode_profilChanged();
    #endregion
	
	public produit()
	{
		this._DetailCommande = new EntitySet<DetailCommande>(new Action<DetailCommande>(this.attach_DetailCommande), new Action<DetailCommande>(this.detach_DetailCommande));
		this._profil = default(EntityRef<profil>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_produit", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id_produit
	{
		get
		{
			return this._Id_produit;
		}
		set
		{
			if ((this._Id_produit != value))
			{
				this.OnId_produitChanging(value);
				this.SendPropertyChanging();
				this._Id_produit = value;
				this.SendPropertyChanged("Id_produit");
				this.OnId_produitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LibelleProduit", DbType="NChar(10)")]
	public string LibelleProduit
	{
		get
		{
			return this._LibelleProduit;
		}
		set
		{
			if ((this._LibelleProduit != value))
			{
				this.OnLibelleProduitChanging(value);
				this.SendPropertyChanging();
				this._LibelleProduit = value;
				this.SendPropertyChanged("LibelleProduit");
				this.OnLibelleProduitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_profil", DbType="Int")]
	public System.Nullable<int> code_profil
	{
		get
		{
			return this._code_profil;
		}
		set
		{
			if ((this._code_profil != value))
			{
				if (this._profil.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_profilChanging(value);
				this.SendPropertyChanging();
				this._code_profil = value;
				this.SendPropertyChanged("code_profil");
				this.Oncode_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="produit_DetailCommande", Storage="_DetailCommande", ThisKey="Id_produit", OtherKey="id_produit")]
	public EntitySet<DetailCommande> DetailCommande
	{
		get
		{
			return this._DetailCommande;
		}
		set
		{
			this._DetailCommande.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_produit", Storage="_profil", ThisKey="code_profil", OtherKey="code_profil", IsForeignKey=true)]
	public profil profil
	{
		get
		{
			return this._profil.Entity;
		}
		set
		{
			profil previousValue = this._profil.Entity;
			if (((previousValue != value) 
						|| (this._profil.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._profil.Entity = null;
					previousValue.produit.Remove(this);
				}
				this._profil.Entity = value;
				if ((value != null))
				{
					value.produit.Add(this);
					this._code_profil = value.code_profil;
				}
				else
				{
					this._code_profil = default(Nullable<int>);
				}
				this.SendPropertyChanged("profil");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DetailCommande(DetailCommande entity)
	{
		this.SendPropertyChanging();
		entity.produit = this;
	}
	
	private void detach_DetailCommande(DetailCommande entity)
	{
		this.SendPropertyChanging();
		entity.produit = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.profil")]
public partial class profil : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_profil;
	
	private string _description_profil;
	
	private EntitySet<affecter> _affecter;
	
	private EntitySet<produit> _produit;
	
	private EntitySet<Utilisateur> _Utilisateur;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_profilChanging(int value);
    partial void Oncode_profilChanged();
    partial void Ondescription_profilChanging(string value);
    partial void Ondescription_profilChanged();
    #endregion
	
	public profil()
	{
		this._affecter = new EntitySet<affecter>(new Action<affecter>(this.attach_affecter), new Action<affecter>(this.detach_affecter));
		this._produit = new EntitySet<produit>(new Action<produit>(this.attach_produit), new Action<produit>(this.detach_produit));
		this._Utilisateur = new EntitySet<Utilisateur>(new Action<Utilisateur>(this.attach_Utilisateur), new Action<Utilisateur>(this.detach_Utilisateur));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_profil", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_profil
	{
		get
		{
			return this._code_profil;
		}
		set
		{
			if ((this._code_profil != value))
			{
				this.Oncode_profilChanging(value);
				this.SendPropertyChanging();
				this._code_profil = value;
				this.SendPropertyChanged("code_profil");
				this.Oncode_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description_profil", DbType="NVarChar(MAX)")]
	public string description_profil
	{
		get
		{
			return this._description_profil;
		}
		set
		{
			if ((this._description_profil != value))
			{
				this.Ondescription_profilChanging(value);
				this.SendPropertyChanging();
				this._description_profil = value;
				this.SendPropertyChanged("description_profil");
				this.Ondescription_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_affecter", Storage="_affecter", ThisKey="code_profil", OtherKey="code_profil")]
	public EntitySet<affecter> affecter
	{
		get
		{
			return this._affecter;
		}
		set
		{
			this._affecter.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_produit", Storage="_produit", ThisKey="code_profil", OtherKey="code_profil")]
	public EntitySet<produit> produit
	{
		get
		{
			return this._produit;
		}
		set
		{
			this._produit.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_Utilisateur", Storage="_Utilisateur", ThisKey="code_profil", OtherKey="code_profil")]
	public EntitySet<Utilisateur> Utilisateur
	{
		get
		{
			return this._Utilisateur;
		}
		set
		{
			this._Utilisateur.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_affecter(affecter entity)
	{
		this.SendPropertyChanging();
		entity.profil = this;
	}
	
	private void detach_affecter(affecter entity)
	{
		this.SendPropertyChanging();
		entity.profil = null;
	}
	
	private void attach_produit(produit entity)
	{
		this.SendPropertyChanging();
		entity.profil = this;
	}
	
	private void detach_produit(produit entity)
	{
		this.SendPropertyChanging();
		entity.profil = null;
	}
	
	private void attach_Utilisateur(Utilisateur entity)
	{
		this.SendPropertyChanging();
		entity.profil = this;
	}
	
	private void detach_Utilisateur(Utilisateur entity)
	{
		this.SendPropertyChanging();
		entity.profil = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.recuperationMDP")]
public partial class recuperationMDP : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Hash;
	
	private string _Etat;
	
	private System.Nullable<int> _code_adresse;
	
	private EntityRef<adresse> _adresse;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHashChanging(string value);
    partial void OnHashChanged();
    partial void OnEtatChanging(string value);
    partial void OnEtatChanged();
    partial void Oncode_adresseChanging(System.Nullable<int> value);
    partial void Oncode_adresseChanged();
    #endregion
	
	public recuperationMDP()
	{
		this._adresse = default(EntityRef<adresse>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hash", DbType="NVarChar(MAX)")]
	public string Hash
	{
		get
		{
			return this._Hash;
		}
		set
		{
			if ((this._Hash != value))
			{
				this.OnHashChanging(value);
				this.SendPropertyChanging();
				this._Hash = value;
				this.SendPropertyChanged("Hash");
				this.OnHashChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="NVarChar(50)")]
	public string Etat
	{
		get
		{
			return this._Etat;
		}
		set
		{
			if ((this._Etat != value))
			{
				this.OnEtatChanging(value);
				this.SendPropertyChanging();
				this._Etat = value;
				this.SendPropertyChanged("Etat");
				this.OnEtatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_adresse", DbType="Int")]
	public System.Nullable<int> code_adresse
	{
		get
		{
			return this._code_adresse;
		}
		set
		{
			if ((this._code_adresse != value))
			{
				if (this._adresse.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_adresseChanging(value);
				this.SendPropertyChanging();
				this._code_adresse = value;
				this.SendPropertyChanged("code_adresse");
				this.Oncode_adresseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="adresse_recuperationMDP", Storage="_adresse", ThisKey="code_adresse", OtherKey="code_adresse", IsForeignKey=true)]
	public adresse adresse
	{
		get
		{
			return this._adresse.Entity;
		}
		set
		{
			adresse previousValue = this._adresse.Entity;
			if (((previousValue != value) 
						|| (this._adresse.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._adresse.Entity = null;
					previousValue.recuperationMDP.Remove(this);
				}
				this._adresse.Entity = value;
				if ((value != null))
				{
					value.recuperationMDP.Add(this);
					this._code_adresse = value.code_adresse;
				}
				else
				{
					this._code_adresse = default(Nullable<int>);
				}
				this.SendPropertyChanged("adresse");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.service")]
public partial class service : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_service;
	
	private System.Nullable<int> _num_contrat;
	
	private System.Nullable<int> _taux;
	
	private int _id_sous_branche;
	
	private System.Nullable<int> _id_type;
	
	private string _etat;
	
	private System.Nullable<System.DateTime> _date_demande;
	
	private System.Nullable<System.DateTime> _date_Reponse;
	
	private string _reponse;
	
	private System.Nullable<int> _duree;
	
	private string _libelleService;
	
	private string _contenu_Reclamation;
	
	private System.Nullable<int> _code_dest;
	
	private System.Nullable<decimal> _primeHTax;
	
	private System.Nullable<decimal> _coutPolice;
	
	private System.Nullable<decimal> _primeTotal;
	
	private System.Nullable<decimal> _tax;
	
	private System.Nullable<int> _code_utilisateur;
	
	private EntitySet<DetailCommande> _DetailCommande;
	
	private EntityRef<sous_branche> _sous_branche;
	
	private EntityRef<type_service> _type_service;
	
	private EntityRef<Utilisateur> _Utilisateur;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_serviceChanging(int value);
    partial void Oncode_serviceChanged();
    partial void Onnum_contratChanging(System.Nullable<int> value);
    partial void Onnum_contratChanged();
    partial void OntauxChanging(System.Nullable<int> value);
    partial void OntauxChanged();
    partial void Onid_sous_brancheChanging(int value);
    partial void Onid_sous_brancheChanged();
    partial void Onid_typeChanging(System.Nullable<int> value);
    partial void Onid_typeChanged();
    partial void OnetatChanging(string value);
    partial void OnetatChanged();
    partial void Ondate_demandeChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_demandeChanged();
    partial void Ondate_ReponseChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_ReponseChanged();
    partial void OnreponseChanging(string value);
    partial void OnreponseChanged();
    partial void OndureeChanging(System.Nullable<int> value);
    partial void OndureeChanged();
    partial void OnlibelleServiceChanging(string value);
    partial void OnlibelleServiceChanged();
    partial void Oncontenu_ReclamationChanging(string value);
    partial void Oncontenu_ReclamationChanged();
    partial void Oncode_destChanging(System.Nullable<int> value);
    partial void Oncode_destChanged();
    partial void OnprimeHTaxChanging(System.Nullable<decimal> value);
    partial void OnprimeHTaxChanged();
    partial void OncoutPoliceChanging(System.Nullable<decimal> value);
    partial void OncoutPoliceChanged();
    partial void OnprimeTotalChanging(System.Nullable<decimal> value);
    partial void OnprimeTotalChanged();
    partial void OntaxChanging(System.Nullable<decimal> value);
    partial void OntaxChanged();
    partial void Oncode_utilisateurChanging(System.Nullable<int> value);
    partial void Oncode_utilisateurChanged();
    #endregion
	
	public service()
	{
		this._DetailCommande = new EntitySet<DetailCommande>(new Action<DetailCommande>(this.attach_DetailCommande), new Action<DetailCommande>(this.detach_DetailCommande));
		this._sous_branche = default(EntityRef<sous_branche>);
		this._type_service = default(EntityRef<type_service>);
		this._Utilisateur = default(EntityRef<Utilisateur>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_service", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int code_service
	{
		get
		{
			return this._code_service;
		}
		set
		{
			if ((this._code_service != value))
			{
				this.Oncode_serviceChanging(value);
				this.SendPropertyChanging();
				this._code_service = value;
				this.SendPropertyChanged("code_service");
				this.Oncode_serviceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_contrat", DbType="Int")]
	public System.Nullable<int> num_contrat
	{
		get
		{
			return this._num_contrat;
		}
		set
		{
			if ((this._num_contrat != value))
			{
				this.Onnum_contratChanging(value);
				this.SendPropertyChanging();
				this._num_contrat = value;
				this.SendPropertyChanged("num_contrat");
				this.Onnum_contratChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taux", DbType="Int")]
	public System.Nullable<int> taux
	{
		get
		{
			return this._taux;
		}
		set
		{
			if ((this._taux != value))
			{
				this.OntauxChanging(value);
				this.SendPropertyChanging();
				this._taux = value;
				this.SendPropertyChanged("taux");
				this.OntauxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_sous_branche", DbType="Int NOT NULL")]
	public int id_sous_branche
	{
		get
		{
			return this._id_sous_branche;
		}
		set
		{
			if ((this._id_sous_branche != value))
			{
				if (this._sous_branche.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_sous_brancheChanging(value);
				this.SendPropertyChanging();
				this._id_sous_branche = value;
				this.SendPropertyChanged("id_sous_branche");
				this.Onid_sous_brancheChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_type", DbType="Int")]
	public System.Nullable<int> id_type
	{
		get
		{
			return this._id_type;
		}
		set
		{
			if ((this._id_type != value))
			{
				if (this._type_service.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_typeChanging(value);
				this.SendPropertyChanging();
				this._id_type = value;
				this.SendPropertyChanged("id_type");
				this.Onid_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etat", DbType="NChar(10)")]
	public string etat
	{
		get
		{
			return this._etat;
		}
		set
		{
			if ((this._etat != value))
			{
				this.OnetatChanging(value);
				this.SendPropertyChanging();
				this._etat = value;
				this.SendPropertyChanged("etat");
				this.OnetatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_demande", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_demande
	{
		get
		{
			return this._date_demande;
		}
		set
		{
			if ((this._date_demande != value))
			{
				this.Ondate_demandeChanging(value);
				this.SendPropertyChanging();
				this._date_demande = value;
				this.SendPropertyChanged("date_demande");
				this.Ondate_demandeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_Reponse", DbType="DateTime")]
	public System.Nullable<System.DateTime> date_Reponse
	{
		get
		{
			return this._date_Reponse;
		}
		set
		{
			if ((this._date_Reponse != value))
			{
				this.Ondate_ReponseChanging(value);
				this.SendPropertyChanging();
				this._date_Reponse = value;
				this.SendPropertyChanged("date_Reponse");
				this.Ondate_ReponseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reponse", DbType="NVarChar(MAX)")]
	public string reponse
	{
		get
		{
			return this._reponse;
		}
		set
		{
			if ((this._reponse != value))
			{
				this.OnreponseChanging(value);
				this.SendPropertyChanging();
				this._reponse = value;
				this.SendPropertyChanged("reponse");
				this.OnreponseChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duree", DbType="Int")]
	public System.Nullable<int> duree
	{
		get
		{
			return this._duree;
		}
		set
		{
			if ((this._duree != value))
			{
				this.OndureeChanging(value);
				this.SendPropertyChanging();
				this._duree = value;
				this.SendPropertyChanged("duree");
				this.OndureeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelleService", DbType="NVarChar(50)")]
	public string libelleService
	{
		get
		{
			return this._libelleService;
		}
		set
		{
			if ((this._libelleService != value))
			{
				this.OnlibelleServiceChanging(value);
				this.SendPropertyChanging();
				this._libelleService = value;
				this.SendPropertyChanged("libelleService");
				this.OnlibelleServiceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contenu_Reclamation", DbType="NVarChar(MAX)")]
	public string contenu_Reclamation
	{
		get
		{
			return this._contenu_Reclamation;
		}
		set
		{
			if ((this._contenu_Reclamation != value))
			{
				this.Oncontenu_ReclamationChanging(value);
				this.SendPropertyChanging();
				this._contenu_Reclamation = value;
				this.SendPropertyChanged("contenu_Reclamation");
				this.Oncontenu_ReclamationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_dest", DbType="Int")]
	public System.Nullable<int> code_dest
	{
		get
		{
			return this._code_dest;
		}
		set
		{
			if ((this._code_dest != value))
			{
				this.Oncode_destChanging(value);
				this.SendPropertyChanging();
				this._code_dest = value;
				this.SendPropertyChanged("code_dest");
				this.Oncode_destChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primeHTax", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> primeHTax
	{
		get
		{
			return this._primeHTax;
		}
		set
		{
			if ((this._primeHTax != value))
			{
				this.OnprimeHTaxChanging(value);
				this.SendPropertyChanging();
				this._primeHTax = value;
				this.SendPropertyChanged("primeHTax");
				this.OnprimeHTaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coutPolice", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> coutPolice
	{
		get
		{
			return this._coutPolice;
		}
		set
		{
			if ((this._coutPolice != value))
			{
				this.OncoutPoliceChanging(value);
				this.SendPropertyChanging();
				this._coutPolice = value;
				this.SendPropertyChanged("coutPolice");
				this.OncoutPoliceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_primeTotal", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> primeTotal
	{
		get
		{
			return this._primeTotal;
		}
		set
		{
			if ((this._primeTotal != value))
			{
				this.OnprimeTotalChanging(value);
				this.SendPropertyChanging();
				this._primeTotal = value;
				this.SendPropertyChanged("primeTotal");
				this.OnprimeTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax", DbType="Decimal(18,3)")]
	public System.Nullable<decimal> tax
	{
		get
		{
			return this._tax;
		}
		set
		{
			if ((this._tax != value))
			{
				this.OntaxChanging(value);
				this.SendPropertyChanging();
				this._tax = value;
				this.SendPropertyChanged("tax");
				this.OntaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_utilisateur", DbType="Int")]
	public System.Nullable<int> code_utilisateur
	{
		get
		{
			return this._code_utilisateur;
		}
		set
		{
			if ((this._code_utilisateur != value))
			{
				if (this._Utilisateur.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_utilisateurChanging(value);
				this.SendPropertyChanging();
				this._code_utilisateur = value;
				this.SendPropertyChanged("code_utilisateur");
				this.Oncode_utilisateurChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="service_DetailCommande", Storage="_DetailCommande", ThisKey="code_service", OtherKey="code_service")]
	public EntitySet<DetailCommande> DetailCommande
	{
		get
		{
			return this._DetailCommande;
		}
		set
		{
			this._DetailCommande.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sous_branche_service", Storage="_sous_branche", ThisKey="id_sous_branche", OtherKey="Id_sous_branche", IsForeignKey=true)]
	public sous_branche sous_branche
	{
		get
		{
			return this._sous_branche.Entity;
		}
		set
		{
			sous_branche previousValue = this._sous_branche.Entity;
			if (((previousValue != value) 
						|| (this._sous_branche.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._sous_branche.Entity = null;
					previousValue.service.Remove(this);
				}
				this._sous_branche.Entity = value;
				if ((value != null))
				{
					value.service.Add(this);
					this._id_sous_branche = value.Id_sous_branche;
				}
				else
				{
					this._id_sous_branche = default(int);
				}
				this.SendPropertyChanged("sous_branche");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="type_service_service", Storage="_type_service", ThisKey="id_type", OtherKey="Id_type", IsForeignKey=true)]
	public type_service type_service
	{
		get
		{
			return this._type_service.Entity;
		}
		set
		{
			type_service previousValue = this._type_service.Entity;
			if (((previousValue != value) 
						|| (this._type_service.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._type_service.Entity = null;
					previousValue.service.Remove(this);
				}
				this._type_service.Entity = value;
				if ((value != null))
				{
					value.service.Add(this);
					this._id_type = value.Id_type;
				}
				else
				{
					this._id_type = default(Nullable<int>);
				}
				this.SendPropertyChanged("type_service");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_service", Storage="_Utilisateur", ThisKey="code_utilisateur", OtherKey="code_utilisateur", IsForeignKey=true)]
	public Utilisateur Utilisateur
	{
		get
		{
			return this._Utilisateur.Entity;
		}
		set
		{
			Utilisateur previousValue = this._Utilisateur.Entity;
			if (((previousValue != value) 
						|| (this._Utilisateur.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Utilisateur.Entity = null;
					previousValue.service.Remove(this);
				}
				this._Utilisateur.Entity = value;
				if ((value != null))
				{
					value.service.Add(this);
					this._code_utilisateur = value.code_utilisateur;
				}
				else
				{
					this._code_utilisateur = default(Nullable<int>);
				}
				this.SendPropertyChanged("Utilisateur");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DetailCommande(DetailCommande entity)
	{
		this.SendPropertyChanging();
		entity.service = this;
	}
	
	private void detach_DetailCommande(DetailCommande entity)
	{
		this.SendPropertyChanging();
		entity.service = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sous_branche")]
public partial class sous_branche : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_sous_branche;
	
	private string _libelle;
	
	private System.Nullable<int> _Id_branche;
	
	private EntitySet<service> _service;
	
	private EntityRef<branche> _branche;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_sous_brancheChanging(int value);
    partial void OnId_sous_brancheChanged();
    partial void OnlibelleChanging(string value);
    partial void OnlibelleChanged();
    partial void OnId_brancheChanging(System.Nullable<int> value);
    partial void OnId_brancheChanged();
    #endregion
	
	public sous_branche()
	{
		this._service = new EntitySet<service>(new Action<service>(this.attach_service), new Action<service>(this.detach_service));
		this._branche = default(EntityRef<branche>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_sous_branche", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id_sous_branche
	{
		get
		{
			return this._Id_sous_branche;
		}
		set
		{
			if ((this._Id_sous_branche != value))
			{
				this.OnId_sous_brancheChanging(value);
				this.SendPropertyChanging();
				this._Id_sous_branche = value;
				this.SendPropertyChanged("Id_sous_branche");
				this.OnId_sous_brancheChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelle", DbType="NVarChar(50)")]
	public string libelle
	{
		get
		{
			return this._libelle;
		}
		set
		{
			if ((this._libelle != value))
			{
				this.OnlibelleChanging(value);
				this.SendPropertyChanging();
				this._libelle = value;
				this.SendPropertyChanged("libelle");
				this.OnlibelleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_branche", DbType="Int")]
	public System.Nullable<int> Id_branche
	{
		get
		{
			return this._Id_branche;
		}
		set
		{
			if ((this._Id_branche != value))
			{
				if (this._branche.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnId_brancheChanging(value);
				this.SendPropertyChanging();
				this._Id_branche = value;
				this.SendPropertyChanged("Id_branche");
				this.OnId_brancheChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="sous_branche_service", Storage="_service", ThisKey="Id_sous_branche", OtherKey="id_sous_branche")]
	public EntitySet<service> service
	{
		get
		{
			return this._service;
		}
		set
		{
			this._service.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="branche_sous_branche", Storage="_branche", ThisKey="Id_branche", OtherKey="Id_branche", IsForeignKey=true)]
	public branche branche
	{
		get
		{
			return this._branche.Entity;
		}
		set
		{
			branche previousValue = this._branche.Entity;
			if (((previousValue != value) 
						|| (this._branche.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._branche.Entity = null;
					previousValue.sous_branche.Remove(this);
				}
				this._branche.Entity = value;
				if ((value != null))
				{
					value.sous_branche.Add(this);
					this._Id_branche = value.Id_branche;
				}
				else
				{
					this._Id_branche = default(Nullable<int>);
				}
				this.SendPropertyChanged("branche");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.sous_branche = this;
	}
	
	private void detach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.sous_branche = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.statistique")]
public partial class statistique
{
	
	private string _Agence;
	
	private System.Nullable<double> _Annee;
	
	private System.Nullable<double> _Mois;
	
	private string _Branche;
	
	private string _SousBranche;
	
	private System.Nullable<double> _Sinistre;
	
	private System.Nullable<double> _Prime;
	
	private System.Nullable<double> _SP;
	
	private System.Nullable<double> _Comission;
	
	public statistique()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Agence", DbType="NVarChar(255)")]
	public string Agence
	{
		get
		{
			return this._Agence;
		}
		set
		{
			if ((this._Agence != value))
			{
				this._Agence = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Annee", DbType="Float")]
	public System.Nullable<double> Annee
	{
		get
		{
			return this._Annee;
		}
		set
		{
			if ((this._Annee != value))
			{
				this._Annee = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mois", DbType="Float")]
	public System.Nullable<double> Mois
	{
		get
		{
			return this._Mois;
		}
		set
		{
			if ((this._Mois != value))
			{
				this._Mois = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branche", DbType="NVarChar(255)")]
	public string Branche
	{
		get
		{
			return this._Branche;
		}
		set
		{
			if ((this._Branche != value))
			{
				this._Branche = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SousBranche", DbType="NVarChar(255)")]
	public string SousBranche
	{
		get
		{
			return this._SousBranche;
		}
		set
		{
			if ((this._SousBranche != value))
			{
				this._SousBranche = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sinistre", DbType="Float")]
	public System.Nullable<double> Sinistre
	{
		get
		{
			return this._Sinistre;
		}
		set
		{
			if ((this._Sinistre != value))
			{
				this._Sinistre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prime", DbType="Float")]
	public System.Nullable<double> Prime
	{
		get
		{
			return this._Prime;
		}
		set
		{
			if ((this._Prime != value))
			{
				this._Prime = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SP", DbType="Float")]
	public System.Nullable<double> SP
	{
		get
		{
			return this._SP;
		}
		set
		{
			if ((this._SP != value))
			{
				this._SP = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comission", DbType="Float")]
	public System.Nullable<double> Comission
	{
		get
		{
			return this._Comission;
		}
		set
		{
			if ((this._Comission != value))
			{
				this._Comission = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.type_interaction")]
public partial class type_interaction : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_interaction;
	
	private string _libelle;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_interactionChanging(int value);
    partial void Oncode_interactionChanged();
    partial void OnlibelleChanging(string value);
    partial void OnlibelleChanged();
    #endregion
	
	public type_interaction()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_interaction", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_interaction
	{
		get
		{
			return this._code_interaction;
		}
		set
		{
			if ((this._code_interaction != value))
			{
				this.Oncode_interactionChanging(value);
				this.SendPropertyChanging();
				this._code_interaction = value;
				this.SendPropertyChanged("code_interaction");
				this.Oncode_interactionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelle", DbType="NChar(10)")]
	public string libelle
	{
		get
		{
			return this._libelle;
		}
		set
		{
			if ((this._libelle != value))
			{
				this.OnlibelleChanging(value);
				this.SendPropertyChanging();
				this._libelle = value;
				this.SendPropertyChanged("libelle");
				this.OnlibelleChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.type_service")]
public partial class type_service : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id_type;
	
	private string _libelle;
	
	private string _famille_type;
	
	private EntitySet<service> _service;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnId_typeChanging(int value);
    partial void OnId_typeChanged();
    partial void OnlibelleChanging(string value);
    partial void OnlibelleChanged();
    partial void Onfamille_typeChanging(string value);
    partial void Onfamille_typeChanged();
    #endregion
	
	public type_service()
	{
		this._service = new EntitySet<service>(new Action<service>(this.attach_service), new Action<service>(this.detach_service));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id_type", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id_type
	{
		get
		{
			return this._Id_type;
		}
		set
		{
			if ((this._Id_type != value))
			{
				this.OnId_typeChanging(value);
				this.SendPropertyChanging();
				this._Id_type = value;
				this.SendPropertyChanged("Id_type");
				this.OnId_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_libelle", DbType="NVarChar(50)")]
	public string libelle
	{
		get
		{
			return this._libelle;
		}
		set
		{
			if ((this._libelle != value))
			{
				this.OnlibelleChanging(value);
				this.SendPropertyChanging();
				this._libelle = value;
				this.SendPropertyChanged("libelle");
				this.OnlibelleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_famille_type", DbType="NVarChar(50)")]
	public string famille_type
	{
		get
		{
			return this._famille_type;
		}
		set
		{
			if ((this._famille_type != value))
			{
				this.Onfamille_typeChanging(value);
				this.SendPropertyChanging();
				this._famille_type = value;
				this.SendPropertyChanged("famille_type");
				this.Onfamille_typeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="type_service_service", Storage="_service", ThisKey="Id_type", OtherKey="id_type")]
	public EntitySet<service> service
	{
		get
		{
			return this._service;
		}
		set
		{
			this._service.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.type_service = this;
	}
	
	private void detach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.type_service = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Utilisateur")]
public partial class Utilisateur : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _code_utilisateur;
	
	private string _Nom_utilisateur;
	
	private string _login;
	
	private string _Mdp;
	
	private string _Etat;
	
	private System.Nullable<int> _code_profil;
	
	private System.Nullable<int> _code_partenaire;
	
	private System.Data.Linq.Binary _Image;
	
	private EntitySet<service> _service;
	
	private EntityRef<profil> _profil;
	
	private EntityRef<partenaire> _partenaire;
	
    #region Définitions de méthodes d'extensibilité
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncode_utilisateurChanging(int value);
    partial void Oncode_utilisateurChanged();
    partial void OnNom_utilisateurChanging(string value);
    partial void OnNom_utilisateurChanged();
    partial void OnloginChanging(string value);
    partial void OnloginChanged();
    partial void OnMdpChanging(string value);
    partial void OnMdpChanged();
    partial void OnEtatChanging(string value);
    partial void OnEtatChanged();
    partial void Oncode_profilChanging(System.Nullable<int> value);
    partial void Oncode_profilChanged();
    partial void Oncode_partenaireChanging(System.Nullable<int> value);
    partial void Oncode_partenaireChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    #endregion
	
	public Utilisateur()
	{
		this._service = new EntitySet<service>(new Action<service>(this.attach_service), new Action<service>(this.detach_service));
		this._profil = default(EntityRef<profil>);
		this._partenaire = default(EntityRef<partenaire>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_utilisateur", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int code_utilisateur
	{
		get
		{
			return this._code_utilisateur;
		}
		set
		{
			if ((this._code_utilisateur != value))
			{
				this.Oncode_utilisateurChanging(value);
				this.SendPropertyChanging();
				this._code_utilisateur = value;
				this.SendPropertyChanged("code_utilisateur");
				this.Oncode_utilisateurChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nom_utilisateur", DbType="NVarChar(50)")]
	public string Nom_utilisateur
	{
		get
		{
			return this._Nom_utilisateur;
		}
		set
		{
			if ((this._Nom_utilisateur != value))
			{
				this.OnNom_utilisateurChanging(value);
				this.SendPropertyChanging();
				this._Nom_utilisateur = value;
				this.SendPropertyChanged("Nom_utilisateur");
				this.OnNom_utilisateurChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login", DbType="NVarChar(50)")]
	public string login
	{
		get
		{
			return this._login;
		}
		set
		{
			if ((this._login != value))
			{
				this.OnloginChanging(value);
				this.SendPropertyChanging();
				this._login = value;
				this.SendPropertyChanged("login");
				this.OnloginChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mdp", DbType="NVarChar(50)")]
	public string Mdp
	{
		get
		{
			return this._Mdp;
		}
		set
		{
			if ((this._Mdp != value))
			{
				this.OnMdpChanging(value);
				this.SendPropertyChanging();
				this._Mdp = value;
				this.SendPropertyChanged("Mdp");
				this.OnMdpChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Etat", DbType="NVarChar(50)")]
	public string Etat
	{
		get
		{
			return this._Etat;
		}
		set
		{
			if ((this._Etat != value))
			{
				this.OnEtatChanging(value);
				this.SendPropertyChanging();
				this._Etat = value;
				this.SendPropertyChanged("Etat");
				this.OnEtatChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_profil", DbType="Int")]
	public System.Nullable<int> code_profil
	{
		get
		{
			return this._code_profil;
		}
		set
		{
			if ((this._code_profil != value))
			{
				if (this._profil.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_profilChanging(value);
				this.SendPropertyChanging();
				this._code_profil = value;
				this.SendPropertyChanged("code_profil");
				this.Oncode_profilChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_partenaire", DbType="Int")]
	public System.Nullable<int> code_partenaire
	{
		get
		{
			return this._code_partenaire;
		}
		set
		{
			if ((this._code_partenaire != value))
			{
				if (this._partenaire.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncode_partenaireChanging(value);
				this.SendPropertyChanging();
				this._code_partenaire = value;
				this.SendPropertyChanged("code_partenaire");
				this.Oncode_partenaireChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="Binary(50)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this.OnImageChanging(value);
				this.SendPropertyChanging();
				this._Image = value;
				this.SendPropertyChanged("Image");
				this.OnImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Utilisateur_service", Storage="_service", ThisKey="code_utilisateur", OtherKey="code_utilisateur")]
	public EntitySet<service> service
	{
		get
		{
			return this._service;
		}
		set
		{
			this._service.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="profil_Utilisateur", Storage="_profil", ThisKey="code_profil", OtherKey="code_profil", IsForeignKey=true)]
	public profil profil
	{
		get
		{
			return this._profil.Entity;
		}
		set
		{
			profil previousValue = this._profil.Entity;
			if (((previousValue != value) 
						|| (this._profil.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._profil.Entity = null;
					previousValue.Utilisateur.Remove(this);
				}
				this._profil.Entity = value;
				if ((value != null))
				{
					value.Utilisateur.Add(this);
					this._code_profil = value.code_profil;
				}
				else
				{
					this._code_profil = default(Nullable<int>);
				}
				this.SendPropertyChanged("profil");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="partenaire_Utilisateur", Storage="_partenaire", ThisKey="code_partenaire", OtherKey="code_partenaire", IsForeignKey=true)]
	public partenaire partenaire
	{
		get
		{
			return this._partenaire.Entity;
		}
		set
		{
			partenaire previousValue = this._partenaire.Entity;
			if (((previousValue != value) 
						|| (this._partenaire.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._partenaire.Entity = null;
					previousValue.Utilisateur.Remove(this);
				}
				this._partenaire.Entity = value;
				if ((value != null))
				{
					value.Utilisateur.Add(this);
					this._code_partenaire = value.code_partenaire;
				}
				else
				{
					this._code_partenaire = default(Nullable<int>);
				}
				this.SendPropertyChanged("partenaire");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.Utilisateur = this;
	}
	
	private void detach_service(service entity)
	{
		this.SendPropertyChanging();
		entity.Utilisateur = null;
	}
}
#pragma warning restore 1591
